name: Our Workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v5
      - run: ls -al
      - run: cat .github/workflows/checkout.yml
      
